name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push 1
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./1-base/Dockerfile
          tags: my-image:1-base
      -
        name: Build and push 2
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./2-backslash/Dockerfile
          tags: my-image:2-backslash
      -
        name: Build and push 3
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./3-heredocs/Dockerfile
          tags: my-image:3-heredocs

      -
        name: docker images
        run: docker images my-image

